### ISSUE TITLE
Anchor component improper implement of HasEnabled

### ISSUE THREAD

**Issue by guygoldwasser** [vaadin/flow#10924]
B"H
follow this: https://stackoverflow.com/questions/13955667/disabled-href-tag/13955695
the setEnabled implementation not fit the html way of making <a> being disabled/enabled

Need some workaround implementation for this case e.g. set the href to none when it disabled

**Comment by miguelatvaadin** [comment]
HI @guygoldwasser ,

thanks for submitting the issue.

As a workaround, just add this to your `styles.css`:

```css
a[disabled] {
    pointer-events: none;
    cursor: default;
   /* add whatever other css changes you want to highlight it is disabled (e.g. change color) */
}
```

I will redirect this issue to the proper team.
