### ISSUE TITLE
ViewAccessChecker + hybrid apps compatibility

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#11637]
### Description of the bug / feature

When the route is not found on the server in the hybrid app, the client side calls `flowRoot.$server.leaveNavigation`, which creates a server-side navigation state for `JavaScriptBootstrapUI.ClientViewPlaceholder` target. However, if the security is enabled, `ViewAccessChecker` prevents this from happening by forwarding to login view (obviously, security annotations are missing on `JavaScriptBootstrapUI.ClientViewPlaceholder`). 

### Minimal reproducible example

My test setup:

1. Create and run normal Flow app with enabled security via SVC
2. Install `nuclei` (https://github.com/projectdiscovery/nuclei)
3. Create the following Nuclei template:

```yaml
id: vaadin-flow-ui-creation
info:
  name: Vaadin Flow UI creation
  author: fluorumlabs
  severity: info

requests:
  - raw:
    - |
      GET /?v-r=init&location= HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Chrome/99
      Connection: keep-alive
    - |
      POST /?v-r=uidl&v-uiId={{uiId}} HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Chrome/99
      Connection: keep-alive

      {
        "csrfToken":"{{securityKey}}",
        "rpc":[
            {
                "type":"publishedEventHandler",
                "node":1,
                "templateEventMethodName":"leaveNavigation",
                "templateEventMethodArgs":["no-view"]
            },
        ],
        "syncId":{{syncId}},
        "clientId":{{clientId}}
      }
      
    cookie-reuse: true

    extractors:
      - type: regex
        part: body
        name: securityKey
        group: 1
        internal: true
        regex: 
          - '"Vaadin-Security-Key"\s*:\s*"([^"]+)"'
      - type: regex
        part: body
        name: uiId
        group: 1
        internal: true
        regex: 
          - '"v-uiId"\s*:\s*([0-9]+)'
      - type: regex
        part: body
        name: syncId
        group: 1
        internal: true
        regex: 
          - '"syncId"\s*:\s*([0-9]+)'
      - type: regex
        part: body
        name: clientId
        group: 1
        internal: true
        regex: 
          - '"clientId"\s*:\s*([0-9]+)'
```

4. Run `nuclei -u http://127.0.0.1:8080/ -t vaadin-flow-ui-creation.yaml -debug`

### Expected behavior

No login view in present in the UIDL response

### Actual behavior

```json
[
   {
      "syncId":1,
      "clientId":1,
      "constants":{
         "94e+JcLBjiY=":{
            "}action":false
         },
         "UIgTd5QWIeE=":{
            "}title":false
         },
         "FKjnOj+fhWo=":{
            "}error":false
         },
         "elkHh6P5UP4=":{
            "}description":false
         },
         "jt5ehN4Qt7w=":{
            "event.detail.username":false,
            "}disabled":false,
            "event.detail.password":false
         },
         "uqvzCy8jAQc=":{
            "}opened":false
         }
      },
      "changes":[
         {
            "node":1,
            "type":"splice",
            "feat":2,
            "index":0,
            "addNodes":[
               3
            ]
         },
         {
            "node":3,
            "type":"attach"
         },
         {
            "node":3,
            "type":"put",
            "key":"tag",
            "feat":0,
            "value":"vaadin-login-overlay"
         },
         {
            "node":3,
            "type":"put",
            "key":"_preventAutoEnable",
            "feat":1,
            "value":true
         },
         {
            "node":3,
            "type":"put",
            "key":"action",
            "feat":1,
            "value":"login"
         },
         {
            "node":3,
            "type":"put",
            "key":"disabled",
            "feat":1,
            "value":false
         },
         {
            "node":3,
            "type":"put",
            "key":"opened",
            "feat":1,
            "value":true
         },
         {
            "node":3,
            "type":"put",
            "key":"noForgotPassword",
            "feat":1,
            "value":true
         },
         {
            "node":3,
            "type":"put",
            "key":"i18n",
            "feat":1,
            "value":{
               "additionalInformation":null,
               "errorMessage":{
                  "message":"Check that you have entered the correct username and password and try again.",
                  "title":"Incorrect username or password"
               },
               "form":{
                  "forgotPassword":"Forgot password",
                  "password":"Password",
                  "submit":"Log in",
                  "title":"Log in",
                  "username":"Username"
               },
               "header":{
                  "description":"Login using user/user or admin/admin",
                  "title":"My App"
               }
            }
         },
         {
            "node":3,
            "type":"empty",
            "featType":true,
            "feat":19
         },
         {
            "node":3,
            "type":"put",
            "key":"description-changed",
            "feat":4,
            "value":"elkHh6P5UP4="
         },
         {
            "node":3,
            "type":"put",
            "key":"title-changed",
            "feat":4,
            "value":"UIgTd5QWIeE="
         },
         {
            "node":3,
            "type":"put",
            "key":"error-changed",
            "feat":4,
            "value":"FKjnOj+fhWo="
         },
         {
            "node":3,
            "type":"put",
            "key":"action-changed",
            "feat":4,
            "value":"94e+JcLBjiY="
         },
         {
            "node":3,
            "type":"put",
            "key":"login",
            "feat":4,
            "value":"jt5ehN4Qt7w="
         },
         {
            "node":3,
            "type":"put",
            "key":"opened-changed",
            "feat":4,
            "value":"uqvzCy8jAQc="
         }
      ],
      "execute":[
         [
            null,
            "no-view",
            "setTimeout(() => window.history.pushState($0, '', $1))"
         ],
         [
            null,
            "login",
            "setTimeout(() => window.history.replaceState($0, '', $1))"
         ],
         [
            "Login",
            "document.title = $0"
         ]
      ],
      "timings":[
         2,
         2
      ]
   }
]
```

### Versions:
- Flow version: 8.0.0.rc1
