### ISSUE TITLE
CSS `@keyframes` not applied from styles.css

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#17207]
### Description of the bug

While migrating "legacy" components from the components-folder to the "new" styling approach based without the components folder, I noticed that `@keyframes` / animations aren't applied / useable. 

### Expected behavior

The label of the button is spinning (in both examples).

### Minimal reproducible example

Working solution: 

/components/vaadin-button.css

```css
[part='label'] {
  animation: button-text 1s ease infinite;
}

@keyframes button-test {
  from {
    transform: rotate(0turn);
  }

  to {
    transform: rotate(1turn);
  }
}
```

Broken:

/styles.css 
and 
@CssImport('blaaa.css')

```css
vaadin-button::part(label) {
  animation: button-text 1s ease infinite;
}

@keyframes button-test {
  from {
    transform: rotate(0turn);
  }

  to {
    transform: rotate(1turn);
  }
}
```

### Versions

- Vaadin / Flow version: 24.1 (probably never worked?)
