### ISSUE TITLE
Uploading files give "Upload forbiddeb" with a 404

### ISSUE THREAD

**Issue by khauser** [vaadin/flow#21354]
### Description of the bug

I do have a vaadin webcomponent with some upload functionality to an azure blob storage. The WC is used behind a simple node.js-proxy. Since a week or so I'm not able to upload any file. There is no log-entry and I just get an `Upload forbidden`. Also I don't see anything I might have changed that could have caused this behavior.

![Image](https://github.com/user-attachments/assets/fbfffcc8-30ba-40d0-99dc-d3e72d4ec005)

### Expected behavior

Upload succeeds

### Minimal reproducible example

Here is some code I use to test the upload:

```java
    private void openUploadDialog()
    {
        MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
        Upload upload = new Upload(buffer);
        upload.setAutoUpload(false);
        upload.setWidthFull();

        Button uploadAll = new Button("Upload All", e -> upload.getElement().callJsFunction("uploadFiles"));

        Dialog dialog = new Dialog();
        dialog.setHeaderTitle("Upload Files");
        dialog.setWidth("400px");
        dialog.add(upload, uploadAll);
        dialog.open();

        upload.addFileRejectedListener(event -> {
            String errorMessage = event.getErrorMessage();

            Notification notification = Notification.show(errorMessage, 5000,
                    Notification.Position.MIDDLE);
            notification.addThemeVariants(NotificationVariant.LUMO_ERROR);
        });

        upload.addSucceededListener(event -> {
            String fileName = event.getFileName();
            InputStream inputStream = buffer.getInputStream(fileName);
            Notification notification = Notification.show("Hallo", 5000, Notification.Position.MIDDLE);
            notification.addThemeVariants(NotificationVariant.LUMO_SUCCESS);
        });
    }
```
I do have a small reproducer for some other issue, but If I add the code there it is working.

Because of [#18945](https://github.com/vaadin/flow/issues/18945) I now added some debug log:
```
quarkus:
  log:
    level: INFO
    category:
      "com.vaadin.flow.server.communication":
        level: DEBUG
```
and see some new of these entries if I execute the upload:
```
> :qu2025-04-25 13:40:41,211 DEBUG [com.vaa.flo.ser.com.UidlWriter] (executor-thread-4) * Creating response to client
> :qu2025-04-25 13:40:41,314 DEBUG [com.vaa.flo.ser.com.UidlWriter] (executor-thread-1) * Creating response to client
```

Do you have any Ideas what more I can log?

### Versions

- Vaadin / Flow version: 24.7.2
- Java version: Java(TM) SE Runtime Environment Oracle GraalVM 21.0.7+8.1 (build 21.0.7+8-LTS-jvmci-23.1-b60)
- OS version: Windows 11
- Browser version (if applicable): Firefox
- Application Server (if applicable): Quarkus
- IDE (if applicable): Eclipse

**Comment by Legioth** [comment]
I see there's an `OPTIONS` request for each "regular" request. This implies that CORS is used which might cause various issues?

The error itself is most likely from https://github.com/vaadin/flow/blob/a736aeb229e84418cccfa056e5d73fc64424ac02/flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java#L102 which implies that there is no "stream resource" registered for that URL in the current session. You can put a breakpoint at that line to check if this is the source of the error.

**Comment by khauser** [comment]
![Image](https://github.com/user-attachments/assets/9ad60511-d3c4-40da-8767-becb59b0f13f)

You are right, the `VAADIN/dynamic/resource/1/81dc7548-d058-4645-ac8b-894ed558960e/upload` seems to return null.

Here are is my cors-configuration:

```
quarkus:
  http:
    cors:
      ~: true
      origins: http://localhost:3000
      headers: accept, authorization, content-type, x-requested-with, x-devmodepoll
      methods: GET, OPTIONS, POST, PUT, DELETE, HEAD
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true
```
