### ISSUE TITLE
Unable to use WebJar resources (fonts, etc.) from application stylesheet

### ISSUE THREAD

**Issue by lightoze** [vaadin/flow#4601]
Use case:
- WebJar with resources is in dependencies
- application stylesheet is trying to refer to those dependencies

What happens:
- relative URL changes when in production mode and links become broken

Here is an example project: https://github.com/lightoze/vaadin-bugs/tree/webjar-resource
I attempt to use roboto-fontface WebJar resources from application-specific style either with `@StyleSheet` or `@HtmlImport` (you can switch between them in `MainView.java`). In both cases in production mode stylesheet URLs are broken.

**Comment by heruan** [comment]
I have a similar issue: font files referenced in a stylesheet and used in a web component are not bundled.

```css
@font-face {
    font-family: 'Dax';
    src: url('fonts/Dax.eot');
    ...
    font-weight: 200;
    font-style: normal;
}
```

```html
<link rel="stylesheet" href="dax.css">

<dom-module id="vinci-logo">
  <template>
    <svg version="1.1" ...>
        <text font-family="Dax" ...>[[division]]</text>
    </svg>
  </template>
...
```

When running in production I get 404s for `fonts/Dax.eot` (and other formats).
