### ISSUE TITLE
add default body styles in the generated index.html

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6877]
When upgrading from V14 to V15 I want the application to have the same default body styles as in V14 so that I do not have to take an extra change during the migration.

DoD:
The generated `index.html` file has the same default for the `<body>` element as in V14 apps:
```css
body {
  height: 100vh;
  width: 100vw;
  margin: 0;
}
```
