### ISSUE TITLE
Java-side resource is not available if resource not referenced in a CSS file

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#9622]
Changing the style on java side, like below
```java
getElement().getStyle().set("background-image",
                "url('theme/my-theme/images/background.jpg')");
```
does not work if the resource (`background.jpg` in our case) is not mentioned in any CSS file within `/theme/my-theme/` folder. But it does work, if adding the reference to that resource (whatever the target element is), for example:
```css
.some-target {
    background: url("./images/background.jpg");
}
```
It impacts both the dev and production mode.
