### ISSUE TITLE
The @Theme annotation should work also in Fusion apps

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9684]
When adding a `@Theme("my-theme")` annotation on the application shell class in Java, I expect the `my-theme` to apply to the application globally without me making any other changes to the app, so that my DX does not differ between Flow and Fusion apps. With Vaadin 19.0-SNAPSHOT this is not the case.

**Steps to reproduce**:
 - download a simple Fusion app from https://start.vaadin.com/?preset=fusion
 - change the Vaadin version to 19.0-SNAPSHOT
 - add a custom theme called `not-lumo` into `frontend/themes/not-lumo` with a single `document.css` file with the following contents
    ```css
    html, :host {
        --lumo-primary-color: red;
        --lumo-primary-text-color: red;
        --lumo-border-radius: 0;
    }
    ```
- add a `@Theme("not-lumo")` annotation on the `com.example.application.Application` Java class
- start the app with `mvn`
- see that the theme does not get applied
- add the following 2 lines into `frontend/index.ts` to apply the theme manually:
    ```ts
    // @ts-ignore
    import { applyTheme } from './themes/not-lumo/not-lumo.generated';
    applyTheme(document);
    ```
 - see that now the theme gets applied
